### ISSUE TITLE
Non-regular files in CompareFiles() can have unexpected results

### ISSUE THREAD

**Issue by chadnetzer** [udhos/equalfile#8] opened 2018-10-30 04:38 UTC
The CompareFiles() receiver func can behave in unexpected ways with non-regular files, particularly when used with multi mode.  For example, when character special files are used, such as Unix's /dev/zero or /dev/urandom, the files have a "size" of zero, but will never return an EOF, which can lead to unintuitive result and tricky handling in the code.

To address these and other potential issues, I recommend removing the ability to compare non-regular files from CompareFiles().  This will ensure that the passed in files will have a valid size, which greatly simplifies handling of cases in the CompareFiles() receiver func.  It *will* represent a change of behavior, but at least the change will involve returning a descriptive error, rather than silent failure.  And since the current semantics can be so difficult for user's to get right, I don't expect that are many (or any) cases dependent on it.

The CompareReaders() function can be used to compare non-regular file contents, and it allows the user better control over comparison and error behavior.  For example, LimitedReaders can be used to wrap the *os.File types as io.Readers, and reaching the given limit would produce EOF rather the error for exceeding MaxSize.  Detecting use of LimitReaders could allow ignoring the MaxSize value, since a safe user supplied limit would be available.

Will submit a PR shortly that would make this change if accepted.

**Comment by udhos** [comment] 2018-10-30 17:17
Hi, 

I am unsure about this specific change. I feel a little resistance to generally disable support for directly comparing non-regular files.

I guess there are real use cases for directly comparing non-regular files. For instance, I think one might want to compare named pipes or to compare process substitution:

```
$ cmp <(echo hi) <(echo hello)
/dev/fd/63 /dev/fd/62 differ: byte 2, line 1

$ equal <(echo hi) <(echo hello)
equal: files differ

```

I enjoy the API ability to support those cases directly without forcing the user to revert to the compare reader alternative.

Maybe we should investigate a way to detect the comparison failed due to unexpected maxsize limit.

Or perhaps provide one method regular-only and other method more tolerant towards non-regular files. Or make it an option to reject non-regular files.

Right now I am a bit uncomfortable to reject non-regular files as the sensible default. Just thinking out loud.

**Comment by chadnetzer** [comment] 2018-10-30 18:44
That's understandable.  However I'd say changing the CompareFile() API eliminates the ambiguity about how to handle such files, and thus allows a program like "equal", which may want to support comparing named pipes, to do so by using CompareReader().  In general these non-normal files behave more like Readers than files, since the size is unknown.  This puts the policy handling outside of the equalfiles package, but makes users have to do more work...

It seems at the very least, that supporting Multi mode with such files is tricky and dangerous, since it's keyed by pathname, and pathname is an unreliable indicator of unchanged content in such cases.  Certainly comparing a named pipe in multi-mode, or /dev/urandom, should be disallowed...  So perhaps by making that change, it would allow retaining the current behavior for non-normal files?  I'll think about it some more.

BTW, the first part of the PR I submitted for this issue deals with not modifying the c.Opt.MaxSize value.  It turns out the current release (0.2.0) still gets this incorrect, just because if left uninitialized it'll be set by the first compared file size, which will be confusing.  Even with the previous behavior it can become set to the default by one func (say CompareReader), and then it will apply to the CompareFunc calls unless the user resets it, or uses another Cmp object.  I think fixing that behavior once and for all will be very beneficial, and can be made into it's own separate PR fairly easily.

Thanks for the feedback, it's definite food for thought, and I think there's likely a good path forward that may retain the simplicity of implementing your use case while avoiding some of the trickiness and edge-cases that are currently present.  I may be busy for a day or two, but I'll be working on it and possibly posting and reading followups here.

**Comment by chadnetzer** [comment] 2018-10-30 22:00
Regarding your thoughts on other possible options for handling unexpected maxsize limits, and non-regular files, I'd say it's tempting to want to leave that to the users of the package to decide the policy, while giving them the right tools to do so.  So for example, rather than try to support all the variations within CompareFile(), your "equal" program could instead decide how it wants to handle comparing the same non-regular file, or comparing non-regular to regular file, etc.  The CompareReader() func should give them the appropriate behavior to do so (using LimitReader and/or c.Opt.MaxSize, as well as the other Cmp and CompareFile() options).

Examples of "surprising" behavior of the 'equal' program, for example:

```
$ ./equal /dev/urandom /dev/urandom
equal: files match
```
The above occurs because ForceFileRead is not enabled, but enabling it means the shortcut for normal files (where it's perfectly acceptable) will be disabled.  Also, if it's enabled:

```
$ ./equal /dev/zero /dev/zero
equal(/dev/zero,/dev/zero): error: max read size reached
equal: files differ
```
then comparing /dev/zero reads a lot of data and fails with an error.  A user might expect that the contents of /dev/zero would match itself.  Granted, this could be considered a trivial point, but how about:

```
$ dd if=/dev/zero of=zeros count=1 bs=1k
$ ./equal /dev/zero zeros
equal: files differ
```
having a file full of only zeros not be equal to the content of /dev/zeros seems odd.  And things get much weirder if we use multimode.  For example, with ForceFileRead = true and compareOnMatch=false, this can occur:

```
$ ./equal /dev/urandom /dev/urandom /dev/urandom
equal: files match
```
due to the current way caching works, which I'm hoping to change.

So, this is just to point out that there are many corner cases, and while I think quite a number of them can be fixed or improved, it may not be worth trying to address them all in CompareFile().  It may just be that to write a complete comparison application, a pkg user will have to do their own additional validations before using CompareReader().

That said, let's continue to make small, hopefully sensible steps, and see where it leads.  Maybe most or even all of these quirks can be addressed without too much extra complexity.

**Comment by udhos** [comment] 2018-10-30 22:04
You made good points. I hope to be able to make contributions soon. A little bit busy these days. :)

**Comment by chadnetzer** [comment] 2018-10-30 23:37
Another case to consider (sorry for the info dump, just wanting to get it documented; understand you're busy, I appreciate the feedback when you have time):

Consider another unexpected case such as this:

```
$ equal <(echo hi) <(echo hi)
equal: files match
$ equal <(echo hi) <(echo hi) <(echo hi)
equal: files differ
```

This is the case because multi-mode pairwise-comparison requires reading the process substitution inputs multiple times unless compareOnMatch == false, and the hashing reads it once and depletes it before the bytewise comparison attempts to read more (and gets EOF).  It's tricky to address this issue in Cmd.CompareFile() simply because it doesn't have the information required to know how to best behave...  (interestingly, the pipes seem so have a valid Size(); I assume it may be buffer-size limited, though, and can't be relied upon to not change).

So, one option might be to make a pkg level CompareFiles() func (not receiver func) which takes an arbitrary number of arguments and does a "best effort" comparison:

func CompareFiles(pathnames ...string)

It could then decide how to "best" do the comparisons, ie. whether to use Multi mode, whether to compareOnMatch, etc.  This would give users who want something simple to have an option; it basically would work like the current equal/main.go program, but with more cases covered.  I feel like making such a function more complicated would be okay, as there are still the Cmd.CompareFile() and Cmd.CompareReader() building blocks, which hopefully could be kept simple (or even simplified).  Advanced users could use the Cmd type, and less-advanced could rely on a basic CompareFiles() and/or even CompareReaders() func to do the right thing for them.  It would still have an issue with unbounded inputs, unless we provided extra options, or made it a receiver func with maybe a new constructor that didn't mandate the user choose multi-mode or not, etc.

Anyway, some more food for thought...

BTW: the above result means that, even if just two pipes are compared in multi-mode, with compareOnMatch == true, after the first comparison (the hash) matches and it moves onto the second byte-by-byte comparison, it may just be comparing two empty pipes at that point, rather than content.  For a strong hash like SHA256 it shouldn't matter, but it's still likely not what the user expected.  And with current API it's a bit difficult to address (imo), because the user could request compareOnMatch when it's just not possible.  Maybe, like you indicated, new funcs/constructors/options that explicitly handled these non-regular cases could be made...

**Comment by udhos** [comment] 2018-10-31 15:15
Hi,

I am commenting below on this specific set: https://github.com/udhos/equalfile/issues/8#issuecomment-434485876

I feel we are currently offering a sensible defaults here:

```
$ cmp /dev/urandom /dev/urandom ; echo $?
0

$ equal /dev/urandom /dev/urandom ; echo $?
Debug=false DEBUG=[]
equal: files match
0

$ ./equal /dev/urandom /dev/urandom /dev/urandom
equal: files match

```
And we already provide ways to change that comparison behavior.

This is another case:

```
$ ./equal /dev/zero /dev/zero
equal(/dev/zero,/dev/zero): error: max read size reached
equal: files differ

```
I think the real issue here is how to report partial matching results since one can never fully compare infinite streams.
We are currently reporting mismatch and maxsize-error.
Do you think we should report match and maxsize-error instead?

Yet another issue:

```
$ dd if=/dev/zero of=zeros count=1 bs=1k
$ ./equal /dev/zero zeros
equal: files differ
```

"having a file full of only zeros not be equal to the content of /dev/zeros seems odd."

I don't quite agree. An infinite stream of zeros ought to be different than a block of zeros, right? For one, they differ in length.

At this point, it remains a bit unclear to me whether providing a different default behavior (rejecting non-regular file) would really improve things.

Hope I am not bothering you with my disagreements. I really appreciated all of your inputs. 

I will look at your other post later.

**Comment by udhos** [comment] 2018-10-31 16:56
Also, maybe we should consider exposing another public method, say CompareRegular(), that would provide a behavior more suitable for regular-only files. We would risk, at worst, gathering more experience on the subject. What do you think?

**Comment by udhos** [comment] 2018-10-31 17:40
Commenting about this one: https://github.com/udhos/equalfile/issues/8#issuecomment-434509825

```
$ equal <(echo hi) <(echo hi)
equal: files match
$ equal <(echo hi) <(echo hi) <(echo hi)
equal: files differ

```

I could not reproduce the effect depicted above.

I am seeing this:

```
$ equal <(echo hi) <(echo hi) ; echo $?
Debug=false DEBUG=[]
equal: files match
0
$ equal <(echo hi) <(echo hi) <(echo hi) ; echo $?
Debug=false DEBUG=[]
equal: files match
0

```

Can you please confirm what you are getting?

**Comment by chadnetzer** [comment] 2018-11-01 03:43
I'll group my responses in this message.

To start, although the examples have been in terms of the 'equal' program, I actually think more in terms of the CompareFile() or CompareReader() func behavior, so I'll try to clarify where I can.  Your feedback on these examples has been helpful in letting me know your perspective as well, and I basically find myself in agreement with it, fwiw.

First, yes, I think that using 'cmp' is a reasonable basis for determining what the default behavior of CompareFile() (and by extension, the 'equal' demo) can be.  It may be a bit Unix-centric, but it also is fairly straightforward if one understands the Unix inode model.  Based on that, and I can see the justification for the results for comparing two files.  For example, the /dev/urandom file behavior makes sense under this mode, and that's fine.

Obviously if someone wanted to write a tool with many more options that handled things differently, I think the equalfile pkg should be able to provide at least the basics for building such a tool, but without taking all the complications on itself.

Regarding the error behavior for exceeding the MaxSize setting, it seems that CompareReader() func itself will return "true", with an error, when exceeding MaxSize, presumably on the assumption that the files were equal up to that point.  However, in your 'equal' program, it then sets the match to "false".  I'm a little torn on what the ideal behavior for the CompareReader/CompareFile funcs should be, but I think it's reasonable that if they return an error when the MaxSize is exceeded, the bool return value should be accurate up to that point.  Then users of the funcs can decide on what the policy for handling such an error is.

At least for CompareReader() the user has the option of providing a LimitedReader to explicitly avoid an error when reaching MaxSize (if they set the MaxSize carefully beforehand), but with CompareFile() it can be trickier unless they do more work before calling it...  In any case, it's something to think about more, and in the meantime I'll likely submit my PR for allowing the CompareReader() call to ignore MaxSize if it is called with LimitedReaders, since that allows the user to indicate a definite max amount of reading, without also having to worry about setting up MaxSize to be larger than the LimitedReader limit.


I like the idea of a CompareRegular() func.  It may simplify things for users who don't need or want to worry about the non-regular file corner cases, and possibly will help keep the CompareFile() implementation simple as well.  It's worth an experimental implementation to try out.


Regarding the following example that I wrote:

```
$ equal <(echo hi) <(echo hi) <(echo hi)
```

I can confirm that the master branch does indeed return "files match", not "files differ", and looking back at my terminal log I see that my result was for a branch I was playing with where non-regular files in multi-mode weren't hashed, but just compared (so that the hashing didn't deplete the input stream).  I neglected to put that in my message and thus mis-stated example, so I apologize for the confusion; I'm getting the same results as you for the master commit.

However, FWIW my original intent with that example was indicate that by using multi-mode with compareOnMatch==true, the result of such cases was subtlety different than what the user might've expected, since the hashing consumes the input, and then the actual byte-per-byte comparison of files is only comparing empty input.  Ie.  it's relying only on the hash for the comparison of content (which is arguably different than what was requested with compareOnMatch==true).  And it may get even trickier when MaxSize is hit; I'll have to think about it more.

Now in truth, relying on the hash value alone for streaming input is possibly what *has* to happen in multi-mode, so it's maybe the most reasonable behavior (and SHA256 can reliably distinguish different content with overwhelming likelihood, so it's not even an issue in practice).

With all that said, first I apologize again for making the example confusing.  :)  But also, secondarily, I'd suggest that this and the other examples could be a documentation issue.  As long as the normal behavior is kept reasonable (which I think with your feedback, it is) these potentially oddball cases can be described with a bit of extra verbiage in either the code and/or the doc.go.  Just mentioning what the CompareFile() behavior will be on non-repeatable stream input, etc. and what to expect when using it with non-regular files.

I think that bit of extra documentation, combined with your CompareRegular() idea, would set me more at ease about some of these use cases while ensuring the code and api remain both flexible and uncomplicated.

Apologies for the long-winded follow up, but again your feedback is very helpful, and I think it sets me straight on my concerns about some of these non-regular file inputs.

I'm satisfied with this issue being closed (if you wish) based on the feedback.  We can continue other discussion in more targeted issues, as they come up, but it's been a helpful thread for me.

**Comment by udhos** [comment] 2018-11-01 13:52
Hi. Just to let you know I appreciated your comments, and also feel there is nothing to apologize about. Discussing all of your inputs is fun and enlightening. Please feel free to close the issue then proceed on any other paths you find interesting. Thanks.

**Comment by udhos** [comment] 2018-11-01 13:56
I have filled another ticket to track one issue you pointed out: https://github.com/udhos/equalfile/issues/11

**Closed as completed** 2018-11-01 19:50 UTC
